import { StyleSheet } from 'react-native';

const gameStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1F1B24',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButton: {
    position: 'absolute',
    top: 50,
    left: 20,
    zIndex: 10,
  },
  backButtonText: {
    fontSize: 26,
    color: '#FF6F61',
    fontFamily: 'Georgia',
    fontWeight: '600',
  },
  header: {
    fontSize: 36,
    fontWeight: '700',
    color: '#FFF',
    marginBottom: 20,
    textAlign: 'center',
    fontFamily: 'Georgia',
  },
  instruction: {
    fontSize: 24,
    color: '#CCC',
    marginBottom: 20,
    textAlign: 'center',
    fontFamily: 'Georgia',
  },
  audioButton: {
    backgroundColor: '#FF6F61',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 40,
    marginBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  audioButtonText: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: '600',
    fontFamily: 'Georgia',
  },
  optionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: 30,
  },
  optionButton: {
    margin: 10,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: '#444',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 4,
    backgroundColor: '#2E2A33',
  },
  optionImage: {
    width: 120,
    height: 120,
    resizeMode: 'contain',
  },
  optionButtonCorrect: {
    borderColor: '#28a745',
    backgroundColor: '#3CB371',
  },
  optionButtonWrong: {
    borderColor: '#dc3545',
    backgroundColor: '#FF6347',
  },
  restartButton: {
    backgroundColor: '#28a745',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 40,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  restartButtonText: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: '600',
    fontFamily: 'Georgia',
  },
  // Modal Styles
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#FFF',
    padding: 30,
    borderRadius: 20,
    alignItems: 'center',
    width: '80%',
  },
  modalText: {
    fontSize: 26,
    fontFamily: 'Georgia',
    fontWeight: '700',
    color: '#333',
    marginBottom: 20,
    textAlign: 'center',
  },
  modalButton: {
    backgroundColor: '#FF6F61',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 30,
  },
  modalButtonText: {
    color: '#FFF',
    fontSize: 22,
    fontFamily: 'Georgia',
    fontWeight: '600',
    // center text
    textAlign: 'center',
  },
});

export default gameStyles;
